import "./globals.css";
import type { Metadata } from "next";
// import { Merriweather } from "next/font/google";

// const font = Merriweather({
//   weight: ["300", "400", "700"],
//   subsets: ["latin-ext"],
// });

export const metadata: Metadata = {
  title: "React Server Functions - Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
